### ISSUE TITLE
Toggle buttons are differ

### ISSUE THREAD

**Issue by vantu5z** [wfpaisa/plane-theme#13]
Toggle buttons are differ in Gnome-shell, Gnome settings and Extensions settings.
![Снимок экрана от 2021-07-22 09-20-07](https://user-images.githubusercontent.com/8698003/126597701-4daa59a6-6e80-4623-ab23-159d101859b5.png)

**Comment by wfpaisa** [comment]
vantu5z I had somewhat forgotten the theme, recently Manjaro migrated to Gnome 40 and I have been migrating the styles, this will take me a few days, thank you very much for reporting the inconsistencies.
![me](https://user-images.githubusercontent.com/1735752/126637472-4d15233a-51b8-4986-97ac-470f000e8d40.png)

**Comment by vantu5z** [comment]
Partly fixed by commit 4f93b4e2cb0c499ca52867ef60e6dc17a2ce338b
Gnome-shell still use different switch button.

**Comment by vantu5z** [comment]
Shell fixed by commit 41f0730993a12b7a11074fb7a8fb1a2e07bee90c
