### ISSUE TITLE
Feature request: colored titlebar version

### ISSUE THREAD

**Issue by Trikenstein** [wfpaisa/plane-theme#16]
This theme is fabulous. Thank you very much. I hope you would consider this request to make an "old school" design which is a dark version with a colored titlebar. If you don't have time, can you prepare the `gtk.css` in a way to allow the user to add color the titlebar. As in the example of [Marwaita GTK3 theme by DarkoMarko42](https://www.gnome-look.org/p/1239855/). Attached is a screenshot of a dark them with a colored titlebar.

I don't know about modern design trends where all windows are all dark or all light. And annoyingly with a macOS imitation. Personally, I have trouble to distinguish overlapping windows. When there is a colored titlebar, I see them better. See example in screenshot 

![Overlapping_Windows_with_colored_titlebar](https://user-images.githubusercontent.com/72353094/127016573-e9edd32e-ff0c-4242-a4c5-59f941c94425.png)

**Comment by wfpaisa** [comment]
Hi @Trikenstein, I want to create a tool where you can choose custom styles, but this tool may take me a while to create.
for the moment you can download the project and change it yourself and compile with `npm run start` with Node v8.


https://github.com/wfpaisa/plane-theme/blob/master/src/gtk-3.0/_common.scss

![image](https://user-images.githubusercontent.com/1735752/127151754-abd1f8cd-cd58-4e9a-b0e3-8bc4834d8cdc.png)

**Comment by Trikenstein** [comment]
Would it be possible if I edit the `gtk.css` file directly? I don't know how to work with `npm` to compile the project

**Comment by wfpaisa** [comment]
ohh, no problem you can!, just open the gtk.css and look for  `* Header bars *` -> background color. and change the `rgba` for one color that you want.  
![image](https://user-images.githubusercontent.com/1735752/127392322-37ee6121-05eb-45bb-8968-ba070a181c18.png)

Tool for generate rgba:
![image](https://user-images.githubusercontent.com/1735752/127392471-3b63bba9-b22c-48d6-b720-b402034e1921.png)


For see the styles you need or reload the shell `Alt + F2` and punto just `r` and Enter or, change the theme adwaita and again chose Plane theme

**Comment by Trikenstein** [comment]
Fantastic! thank you very much. After trying for about half an hour, making some guess changes. I got colored titlebar! Although not working perfectly. GTK2 apps like Audacious, Slack, etc. still have the gray titlebar. Can you please show me where to change for GTK2 apps?

![PlaneDark_coloredTitleBar_custom_gtk-css](https://user-images.githubusercontent.com/72353094/127418540-9af3c9bf-8f10-4212-b9ed-68fec7063d61.png)

**Comment by Trikenstein** [comment]
Hi, FYI also fixed for the titlebar colored theme for GTK2 apps. I noticed the [Marwaita theme by MarkoDarko42](https://www.gnome-look.org/p/1239855/) is able to set the titlebar color for GTK2 identical to the settings used in GTK3. I just replace the `gtk_2-0` directory by that of the Marwaita theme. And somehow it works perfectly with the Plane theme.

```shell
tar -czvf ~/Downloads/Plane-dark-3.36_gtk_2.0_backup.tgz -C ~/.themes Plane-dark-3.36/gtk-2.0
rm -rf ~/.themes/Plane-dark-3.36/gtk-2.0/*
cp ~/.themes/Marwaita\ Dark/gtk-2.0/gtkrc ~/.themes/Plane-dark-3.36/gtk-2.0
```
