### ISSUE TITLE
Nautilus folder context menu (bottom margin)

### ISSUE THREAD

**Issue by vantu5z** [wfpaisa/plane-theme#18]
![Снимок экрана от 2021-07-28 10-05-10](https://user-images.githubusercontent.com/8698003/127279877-a0202663-9c4b-4963-b197-d32476c696a0.png)
This appear only on folder menu, file menu is fine.

**Comment by wfpaisa** [comment]
Ivan, yep, is a style fix on nautilus
![Screenshot from 2021-07-28 07-18-38](https://user-images.githubusercontent.com/1735752/127321144-7b4893f5-2371-48f6-b6e6-f7c13dbc11f9.png)
