### ISSUE TITLE
Firefox maximize, minimize, close button hover behaves wrong after costomize firefox to hide title bar

### ISSUE THREAD

**Issue by fengzj** [wfpaisa/plane-theme#2]
gnome-shell --version：
GNOME Shell 3.30.1

Firefox version:
![image](https://user-images.githubusercontent.com/18002829/46915750-6e024080-cfe2-11e8-8993-08a2692f1dcd.png)

When put mouse on buttons, they do not show the under line or rectangle or cross in the circle:
![screenshot from 2018-10-14 18-58-35](https://user-images.githubusercontent.com/18002829/46915821-dbfb3780-cfe3-11e8-9a54-e9d6ed4b8622.png)

another problem:
Is the search box showing in a right way?
![image](https://user-images.githubusercontent.com/18002829/46915863-7b202f00-cfe4-11e8-993e-a2d3ba382636.png)

**Comment by wfpaisa** [comment]
Yeah, this problem is of Firefox and another applications (chrome,vivaldi...),  I think I'll go back to the previous version with the traditional buttons.
https://forum.manjaro.org/t/rounded-titlebutton-buttons-like-macos-or-normal-what-do-you-prefer/61758
