### ISSUE TITLE
[Request] Fonts more contrast / header bar non transparent

### ISSUE THREAD

**Issue by pkomur** [wfpaisa/plane-theme#5]
Please make fonts darker (more contrasting) and header bar non transparent.

**Comment by wfpaisa** [comment]
Hi pkomur, What variation of the theme do you use, white or dark?

**Comment by pkomur** [comment]
Hi, I use white variant. Dark variant is OK.

**Comment by wfpaisa** [comment]
Hi pkomur,  [done](https://github.com/wfpaisa/plane-theme/commit/c08e3b1bdea534f7131b4a87923093888f2a4818)

**Comment by pkomur** [comment]
Hi, now is much better. Thanks.
