### ISSUE TITLE
Give some more space to the Notification window?

### ISSUE THREAD

**Issue by alosarjos** [wfpaisa/plane-theme#7]
Some extensions like the "Do not disturb" are too close to the limit with this gnome-shell theme. U put a comparison with your theme and the default one.

![captura de pantalla de 2018-12-09 11-32-05](https://user-images.githubusercontent.com/29999427/49696164-3fe64a80-fba6-11e8-824f-ce3d8f501c4e.png)
![captura de pantalla de 2018-12-09 11-32-28](https://user-images.githubusercontent.com/29999427/49696167-4248a480-fba6-11e8-8d36-8a308a6d820f.png)

**Comment by wfpaisa** [comment]
Hi, done (https://github.com/wfpaisa/plane-theme/commit/3f6ab33e16d2c83869900f45d9f1fdca584069bd) ;)
