### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by yochananmarqos** [wfpaisa/plane-theme#9]
Manjaro Linux
GNOME 3.34.4
`nodejs` 13.9.0
`npm` 6.14.0
`gulp` 4.0.2

[Build log](https://pastebin.com/Z3DRcwP0)

As a workaround, I successfully built it using `nvm` to install `npm` 8.16.2 and ran `npm start` instead of `gulp`.

**Comment by wfpaisa** [comment]
Sorrry, is necessary the 8.12.0 Node version.
